version: '3'

services:
  app1:
    build: ./
    image: 'back:1.0'
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: yurec
      SPRING_DATASOURCE_PASSWORD: 2212
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: yurec
      POSTGRES_PASSWORD: 2212
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
